### ISSUE TITLE
Problem when running

### ISSUE THREAD

**Issue by benonymus** [coyle/imap-notify#4]
Hey there,
When I try to run my project I get this error.
\node_modules\imap-notify\lib\imap-notify.js:93
      .sortByAll()
       ^

TypeError: _.chain(...).sortByAll is not a function

**Comment by Revadike** [comment]
Same here:
```
TypeError: _.chain(...).sortByAll is not a function
    at ImapNotify.<anonymous> (.\node_modules\imap-notify\lib\imap-notify.js:93:8)
    at Connection._resTagged (.\node_modules\imap\lib\Connection.js:1535:22)
    at Parser.<anonymous> (.\node_modules\imap\lib\Connection.js:194:10)
    at Parser.emit (events.js:197:13)
    at Parser._resTagged (.\node_modules\imap\lib\Parser.js:175:10)
    at Parser._parse (.\node_modules\imap\lib\Parser.js:139:16)
    at Parser._tryread (.\node_modules\imap\lib\Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (.\node_modules\imap\lib\Parser.js:53:12)
    at TLSSocket.emit (events.js:197:13)
    at emitReadable_ (_stream_readable.js:539:12)
```

**Comment by foadyousefi** [comment]
The reason is `.sortByAll()` is removed from newer versions of lodash and this module uses older versions of it.
